/**
 * Card Image Utilities
 *
 * Maps card IDs to their image paths in the public folder
 *
 * Auto-generated by scripts/add-card-images.sh
 * Last updated: Thu Jan 22 17:11:39 HKT 2026
 */

/**
 * List of cards with images available
 */
const CARDS_WITH_IMAGES = [
    
    'citi-cash-back',
    'dbs-black-world',
    'hang-seng-enjoy',
    'hsbc-everymile',
    'hsbc-red',
    'sc-cathay-priority-banking',
    'sc-cathay-priority-private',
    'sc-cathay-standard',
    'sc-simply-cash',
    'sc-smart'
];

/**
 * Get the image URL for a credit card
 * Returns the image path if available, otherwise returns empty string
 */
export function getCardImageUrl(cardId: string): string {
  if (CARDS_WITH_IMAGES.includes(cardId)) {
    return `/cards/${cardId}.png`;
  }

  // Return empty string for cards without images (fallback handled in component)
  return '';
}

/**
 * Check if a card has an image available
 */
export function hasCardImage(cardId: string): boolean {
  return CARDS_WITH_IMAGES.includes(cardId);
}

/**
 * Get all card IDs that have images
 */
export function getCardsWithImages(): string[] {
  return [...CARDS_WITH_IMAGES];
}

/**
 * Get count of available card images
 */
export function getCardImageCount(): number {
  return CARDS_WITH_IMAGES.length;
}
