#!/bin/bash

###############################################################################
# Card Image Automation Script
#
# This script helps you add new card images to CardGPT
#
# Usage:
#   1. Add card images to card_image/ folder with format: {card-id}.png
#   2. Run: npm run add-card-images
#   3. Script will automatically:
#      - Copy images to public/cards/
#      - Update cardImages.ts with new card IDs
#      - List cards that still need images
###############################################################################

set -e  # Exit on error

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🖼️  CardGPT Image Automation${NC}"
echo "================================"
echo ""

# Check if card_image directory exists
if [ ! -d "card_image" ]; then
    echo -e "${YELLOW}⚠️  card_image/ directory not found${NC}"
    exit 1
fi

# Copy images to public/cards/
echo -e "${GREEN}📂 Copying images to public/cards/${NC}"
mkdir -p public/cards
cp card_image/*.png public/cards/ 2>/dev/null || echo "No PNG files found in card_image/"
cp card_image/*.jpg public/cards/ 2>/dev/null || true
cp card_image/*.jpeg public/cards/ 2>/dev/null || true

# Get list of image files (without extension)
echo ""
echo -e "${GREEN}📋 Detected card images:${NC}"
cd public/cards/
CARD_IDS=()
for file in *.{png,jpg,jpeg}; do
    if [ -f "$file" ]; then
        # Remove extension
        card_id="${file%.*}"
        CARD_IDS+=("$card_id")
        echo "  ✓ $card_id"
    fi
done
cd ../..

# Generate updated cardImages.ts
echo ""
echo -e "${GREEN}🔧 Updating src/lib/cardImages.ts${NC}"

# Create array string for TypeScript
CARDS_ARRAY=$(printf ",\n    '%s'" "${CARD_IDS[@]}")
CARDS_ARRAY=${CARDS_ARRAY:1}  # Remove leading comma

# Write updated cardImages.ts
cat > src/lib/cardImages.ts << EOF
/**
 * Card Image Utilities
 *
 * Maps card IDs to their image paths in the public folder
 *
 * Auto-generated by scripts/add-card-images.sh
 * Last updated: $(date)
 */

/**
 * List of cards with images available
 */
const CARDS_WITH_IMAGES = [
    ${CARDS_ARRAY}
];

/**
 * Get the image URL for a credit card
 * Returns the image path if available, otherwise returns empty string
 */
export function getCardImageUrl(cardId: string): string {
  if (CARDS_WITH_IMAGES.includes(cardId)) {
    return \`/cards/\${cardId}.png\`;
  }

  // Return empty string for cards without images (fallback handled in component)
  return '';
}

/**
 * Check if a card has an image available
 */
export function hasCardImage(cardId: string): boolean {
  return CARDS_WITH_IMAGES.includes(cardId);
}

/**
 * Get all card IDs that have images
 */
export function getCardsWithImages(): string[] {
  return [...CARDS_WITH_IMAGES];
}

/**
 * Get count of available card images
 */
export function getCardImageCount(): number {
  return CARDS_WITH_IMAGES.length;
}
EOF

echo "  ✓ Updated cardImages.ts with ${#CARD_IDS[@]} cards"

# Check which cards in cards.json don't have images
echo ""
echo -e "${BLUE}📊 Card Image Coverage:${NC}"
ALL_CARD_IDS=$(jq -r '.cards[] | .id' src/data/cards.json)

MISSING_IMAGES=()
for card_id in $ALL_CARD_IDS; do
    if [[ ! " ${CARD_IDS[@]} " =~ " ${card_id} " ]]; then
        MISSING_IMAGES+=("$card_id")
    fi
done

echo "  ✓ Cards with images: ${#CARD_IDS[@]}"
echo "  ⚠️  Cards missing images: ${#MISSING_IMAGES[@]}"

if [ ${#MISSING_IMAGES[@]} -gt 0 ]; then
    echo ""
    echo -e "${YELLOW}Missing card images:${NC}"
    for card_id in "${MISSING_IMAGES[@]}"; do
        echo "  - $card_id.png"
    done
    echo ""
    echo -e "${YELLOW}💡 Tip: Add images to card_image/ folder with these filenames and run this script again${NC}"
fi

echo ""
echo -e "${GREEN}✅ Done! Card images updated successfully${NC}"
echo ""
echo "Next steps:"
echo "  1. Test locally: npm run dev"
echo "  2. Verify images appear in recommendations"
echo "  3. Deploy to production"
