/**
 * Auto-generated file - DO NOT EDIT MANUALLY
 * Generated by: npx tsx scripts/generateCategoryMerchants.ts
 *
 * This file contains merchants grouped by spending category,
 * extracted from card rules in cards.json
 *
 * Note: Uses primary brand names only (no bilingual labels)
 * HK users are bilingual and recognize both EN/ZH brand names
 */

import type { TransactionCategory } from '@/types/transaction';

export interface MerchantInfo {
  id: string;
  label: string;  // Primary display name (brand name)
}

export const CATEGORY_MERCHANTS: Record<TransactionCategory, MerchantInfo[]> = {
  'groceries': [
    { id: '7-eleven', label: '7-Eleven' },
    { id: '759-store', label: '759 Store' },
    { id: 'circle-k', label: 'Circle K' },
    { id: 'parknshop', label: 'ParknShop' },
    { id: 'wellcome', label: 'Wellcome' },
  ],
  'dining': [
    { id: 'deliveroo', label: 'Deliveroo' },
    { id: 'foodpanda', label: 'foodpanda' },
    { id: 'mcdonalds', label: "McDonald's" },
    { id: 'openrice', label: 'OpenRice' },
    { id: 'pacific-coffee', label: 'Pacific Coffee' },
    { id: 'starbucks', label: 'Starbucks' },
    { id: 'sushiro', label: 'Sushiro' },
  ],
  'online': [
    { id: 'amazon', label: 'Amazon' },
    { id: 'apple', label: 'Apple' },
    { id: 'hktvmall', label: 'HKTVmall' },
    { id: 'netflix', label: 'Netflix' },
    { id: 'spotify', label: 'Spotify' },
    { id: 'taobao', label: 'Taobao' },
  ],
  'travel': [
    { id: 'agoda', label: 'Agoda' },
    { id: 'cathay-pacific', label: 'Cathay Pacific' },
    { id: 'klook', label: 'Klook' },
  ],
  'transport': [
    { id: 'caltex', label: 'Caltex' },
    { id: 'citybus', label: 'Citybus' },
    { id: 'cityflyer', label: 'Cityflyer' },
    { id: 'esso', label: 'Esso' },
    { id: 'kmb', label: 'KMB' },
    { id: 'lwb', label: 'Lwb' },
    { id: 'mtr', label: 'MTR' },
    { id: 'shell', label: 'Shell' },
    { id: 'star-ferry', label: 'Star Ferry' },
    { id: 'tram', label: 'Tram' },
  ],
  'overseas': [
  ],
  'utilities': [
    { id: 'clp', label: 'CLP' },
    { id: 'hk-electric', label: 'HK Electric' },
    { id: 'towngas', label: 'Towngas' },
  ],
  'financial': [
    { id: 'aia', label: 'AIA' },
    { id: 'manulife', label: 'Manulife' },
    { id: 'prudential', label: 'Prudential' },
  ],
  'government': [
  ],
  'digital-wallet': [
    { id: 'alipay-hk', label: 'AlipayHK' },
    { id: 'octopus', label: 'Octopus' },
    { id: 'payme', label: 'PayMe' },
    { id: 'wechat-pay', label: 'WeChat Pay' },
  ],
  'others': [
    { id: 'adidas', label: 'Adidas' },
    { id: 'cosme-store', label: 'Cosme Store' },
    { id: 'decathlon', label: 'Decathlon' },
    { id: 'fila', label: 'Fila' },
    { id: 'ikea', label: 'IKEA' },
    { id: 'mannings', label: 'Mannings' },
    { id: 'matsukiyo-hk', label: 'Matsukiyo Hk' },
    { id: 'muji', label: 'MUJI' },
    { id: 'puma', label: 'Puma' },
    { id: 'sushiro', label: 'Sushiro' },
    { id: 'tokyo-lifestyle', label: 'Tokyo Lifestyle' },
    { id: 'uniqlo', label: 'UNIQLO' },
    { id: 'watsons', label: 'Watsons' },
  ],
};

/**
 * Get all unique merchants across all categories
 */
export function getAllMerchants(): MerchantInfo[] {
  const seen = new Set<string>();
  const result: MerchantInfo[] = [];

  for (const merchants of Object.values(CATEGORY_MERCHANTS)) {
    for (const merchant of merchants) {
      if (!seen.has(merchant.id)) {
        seen.add(merchant.id);
        result.push(merchant);
      }
    }
  }

  return result.sort((a, b) => a.label.localeCompare(b.label));
}

/**
 * Get merchants for a specific category
 */
export function getMerchantsForCategory(category: TransactionCategory): MerchantInfo[] {
  return CATEGORY_MERCHANTS[category] || [];
}
